info:
  name: Search Applications
  type: http
  seq: 5

http:
  method: GET
  url: http://127.0.0.1:8000/v1/application?first_name=John&page_size=10
  params:
    - name: first_name
      value: John
      type: query
    - name: last_name
      value: Lennon
      type: query
      disabled: true
    - name: employee_id
      value: "2"
      type: query
      disabled: true
    - name: page_size
      value: "10"
      type: query
    - name: page
      value: "1"
      type: query
      disabled: true
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
